name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia según la versión que uses

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages  # Nombre del artefacto
          path: ./dist        # Ruta de salida del build de Vite

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

